//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace HealthIQ.CommonLayer.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Messages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("HealthIQ.CommonLayer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation Your account has been reset..
        /// </summary>
        public static string AccountReset {
            get {
                return ResourceManager.GetString("AccountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to access services..
        /// </summary>
        public static string ApiAccessDenied {
            get {
                return ResourceManager.GetString("ApiAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to access services..
        /// </summary>
        public static string CredentialsNotFound {
            get {
                return ResourceManager.GetString("CredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not use your account with in 3 days. Please reset your password..
        /// </summary>
        public static string DaysExpire {
            get {
                return ResourceManager.GetString("DaysExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete data. Try again later..
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an entry for office training of today&apos;s date..
        /// </summary>
        public static string DuplicateEntry {
            get {
                return ResourceManager.GetString("DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong confirmation ID..
        /// </summary>
        public static string EmpCodeNotValid {
            get {
                return ResourceManager.GetString("EmpCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0} Inner Exception : {1} StackTrace: {2}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong confirmation ID..
        /// </summary>
        public static string ForgetPin {
            get {
                return ResourceManager.GetString("ForgetPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has not been uploaded successfully..
        /// </summary>
        public static string ImageNotSave {
            get {
                return ResourceManager.GetString("ImageNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has uploaded successfully..
        /// </summary>
        public static string ImageSave {
            get {
                return ResourceManager.GetString("ImageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or wrong credentials. Try again!.
        /// </summary>
        public static string ImeiNotValid {
            get {
                return ResourceManager.GetString("ImeiNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is in inactive mode, Contact to your admin ..
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID..
        /// </summary>
        public static string InvalidUserID {
            get {
                return ResourceManager.GetString("InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked, Please reset your password..
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User acccount is inactive. Please Contact your Administrator.
        /// </summary>
        public static string LoginInActive {
            get {
                return ResourceManager.GetString("LoginInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User acccount is locked. Please Contact your Administrator.
        /// </summary>
        public static string LoginLocked {
            get {
                return ResourceManager.GetString("LoginLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successfully..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string LoginWrongPassword {
            get {
                return ResourceManager.GetString("LoginWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string LoginWrongUserId {
            get {
                return ResourceManager.GetString("LoginWrongUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is registed for multiple users..
        /// </summary>
        public static string MultipleIMEI {
            get {
                return ResourceManager.GetString("MultipleIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already login from &lt;div class=&apos;cb&apos;&gt;&lt;/div&gt; IP Address : {0} &lt;/br&gt; Browser : {1}.
        /// </summary>
        public static string MultipleSessionMessage {
            get {
                return ResourceManager.GetString("MultipleSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details couldn&apos;t be updated..
        /// </summary>
        public static string NotUpdatedprofile {
            get {
                return ResourceManager.GetString("NotUpdatedprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded maximum attempts. Please try generating new OTP..
        /// </summary>
        public static string OTPWrongAttempts {
            get {
                return ResourceManager.GetString("OTPWrongAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Complexity is not followed.
        /// </summary>
        public static string PasswordRule {
            get {
                return ResourceManager.GetString("PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session will be terminated. Are you sure?.
        /// </summary>
        public static string TerminateSessionConfirmation {
            get {
                return ResourceManager.GetString("TerminateSessionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details updated successfully..
        /// </summary>
        public static string UpdatedProfile {
            get {
                return ResourceManager.GetString("UpdatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted successfully..
        /// </summary>
        public static string VisitorInserted {
            get {
                return ResourceManager.GetString("VisitorInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Event is successfully deleted..
        /// </summary>
        public static string WeddingEventDeleted {
            get {
                return ResourceManager.GetString("WeddingEventDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wedding subscription is expired on {0}. Please renew to use..
        /// </summary>
        public static string WeddingExpired {
            get {
                return ResourceManager.GetString("WeddingExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding information is failed to submit..
        /// </summary>
        public static string WeddingSubmittedFail {
            get {
                return ResourceManager.GetString("WeddingSubmittedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding information is successfully submitted..
        /// </summary>
        public static string WeddingSubmittedSuccess {
            get {
                return ResourceManager.GetString("WeddingSubmittedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong employee name..
        /// </summary>
        public static string WrongEmployeeName {
            get {
                return ResourceManager.GetString("WrongEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or wrong credential / IMEI Number..
        /// </summary>
        public static string Wrongimi {
            get {
                return ResourceManager.GetString("Wrongimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or wrong credential / IMEI Number..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
